[View in Colaboratory](https://colab.research.google.com/github/oneleo/AIA_2018_2th/blob/master/iris_classification.ipynb)

# Iris Classification

In [0]:
from sklearn.datasets import load_iris
import numpy as np

In [3]:
iris_data = load_iris()
print(iris_data.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


In [4]:
print(iris_data.DESCR)

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [5]:
print(iris_data.data)
print(iris_data.data.shape)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [6]:
print(iris_data.target)
print(iris_data.target.shape)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
(150,)


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target,test_size=0.33, random_state= 42, shuffle=True)

In [0]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train,y_train)
y_test_pred = model.predict(X_test)

# Confusion Matrix

In [9]:
from sklearn import metrics

print('Accuracy:%.2f'%metrics.accuracy_score(y_test, y_test_pred))
print(metrics.confusion_matrix(y_test, y_test_pred))

Accuracy:1.00
[[19  0  0]
 [ 0 15  0]
 [ 0  0 16]]


In [10]:
y_test_pred = model.predict(X_test)
y_test_pred_proba = model.predict_proba(X_test)
print('Classification Output:\n', y_test_pred)
print('Probability Output:\n', y_test_pred_proba)

Classification Output:
 [1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0 0 0 2 1 1 0 0 1 2 2 1 2]
Probability Output:
 [[1.25298758e-02 6.68109800e-01 3.19360324e-01]
 [8.89553501e-01 1.10419767e-01 2.67323166e-05]
 [3.03573432e-05 4.13187824e-01 5.86781818e-01]
 [1.82800122e-02 5.54955195e-01 4.26764793e-01]
 [1.17152929e-02 7.36405053e-01 2.51879654e-01]
 [8.63680511e-01 1.36262048e-01 5.74418999e-05]
 [1.79128050e-01 6.78324666e-01 1.42547284e-01]
 [3.52556308e-03 2.91150243e-01 7.05324194e-01]
 [4.79219667e-03 5.82239040e-01 4.12968764e-01]
 [6.92023914e-02 7.66591464e-01 1.64206144e-01]
 [4.77922595e-03 3.13383550e-01 6.81837224e-01]
 [7.89372758e-01 2.10530561e-01 9.66817939e-05]
 [8.64930398e-01 1.35051719e-01 1.78822315e-05]
 [7.96572373e-01 2.03336535e-01 9.10924809e-05]
 [9.14085715e-01 8.58719771e-02 4.23082488e-05]
 [2.81092156e-02 5.35883167e-01 4.36007618e-01]
 [4.66788820e-04 2.74457224e-01 7.25075988e-01]
 [4.55900829e-02 7.63213143e-01 1.91

# Tuning Logistic Regression - C Parameter

In [11]:
model = LogisticRegression(C=1.0)
model.fit(X_train,y_train)
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)
print('train evaluation---------------------------------')
print('accuracy:%.2f'%metrics.accuracy_score(y_train, y_train_pred))
print('confusion matirx:\n', metrics.confusion_matrix(y_train, y_train_pred))
print('test evaluation---------------------------------')
print('accuracy:%.2f'%metrics.accuracy_score(y_test, y_test_pred))
print('confusion matirx:\n', metrics.confusion_matrix(y_test, y_test_pred))



train evaluation---------------------------------
accuracy:0.95
confusion matirx:
 [[31  0  0]
 [ 0 31  4]
 [ 0  1 33]]
test evaluation---------------------------------
accuracy:1.00
confusion matirx:
 [[19  0  0]
 [ 0 15  0]
 [ 0  0 16]]


# Tuning Logistic Regression - Multi_Class

In [14]:
model = LogisticRegression(solver='sag', multi_class='multinomial',max_iter=3000)
model.fit(X_train,y_train)
y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)
print('train evaluation---------------------------------')
print('accuracy:%.2f'%metrics.accuracy_score(y_train, y_train_pred))
print('confusion matirx:\n', metrics.confusion_matrix(y_train, y_train_pred))
print('test evaluation---------------------------------')
print('accuracy:%.2f'%metrics.accuracy_score(y_test, y_test_pred))
print('confusion matirx:\n', metrics.confusion_matrix(y_test, y_test_pred))

train evaluation---------------------------------
accuracy:0.96
confusion matirx:
 [[31  0  0]
 [ 0 32  3]
 [ 0  1 33]]
test evaluation---------------------------------
accuracy:1.00
confusion matirx:
 [[19  0  0]
 [ 0 15  0]
 [ 0  0 16]]
